### ISSUE TITLE
Breaks .jira.d/config.yml

### ISSUE THREAD

**Issue by rocketraman** [atlassian/gajira-comment#4]
This writes a {} to the last line of .jira.d/config.yml, which breaks any further actions that attempt to read that file, as it is invalid YAML.

The actions.yml always returns an empty object, and because of eemeli/yaml#136 this is stringified to {}.

According to the upstream issue {} is valid YAML. However the code that parses this config borks when it sees the value without any colon. This component should just not write anything to that file.

Same as https://github.com/atlassian/gajira-transition/issues/6.

**Comment by rudzon** [comment]
Hi, this should be fixed in v2.0.2 https://github.com/atlassian/gajira-comment/releases/tag/v2.0.2
